name: Pylinter

on: [push, workflow_dispatch, pull_request]

jobs:
  Static_Analysis_pylint:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Analyzing Code with Pylint
        run: pylint --rcfile .github/workflows/.pylintrc subtitle.py

